// Copyright 2025 Nguyen-Nhat Nguyen
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: api/workflow.proto

package workflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_RUNNING     WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED   WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_FAILED      WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED   WorkflowStatus = 4
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_COMPLETED",
		3: "WORKFLOW_STATUS_FAILED",
		4: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_RUNNING":     1,
		"WORKFLOW_STATUS_COMPLETED":   2,
		"WORKFLOW_STATUS_FAILED":      3,
		"WORKFLOW_STATUS_CANCELLED":   4,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_api_workflow_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED        EventType = 0
	EventType_EVENT_TYPE_WORKFLOW_STARTED   EventType = 1
	EventType_EVENT_TYPE_WORKFLOW_COMPLETED EventType = 2
	EventType_EVENT_TYPE_WORKFLOW_FAILED    EventType = 3
	EventType_EVENT_TYPE_ACTIVITY_SCHEDULED EventType = 4
	EventType_EVENT_TYPE_ACTIVITY_STARTED   EventType = 5
	EventType_EVENT_TYPE_ACTIVITY_COMPLETED EventType = 6
	EventType_EVENT_TYPE_ACTIVITY_FAILED    EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_WORKFLOW_STARTED",
		2: "EVENT_TYPE_WORKFLOW_COMPLETED",
		3: "EVENT_TYPE_WORKFLOW_FAILED",
		4: "EVENT_TYPE_ACTIVITY_SCHEDULED",
		5: "EVENT_TYPE_ACTIVITY_STARTED",
		6: "EVENT_TYPE_ACTIVITY_COMPLETED",
		7: "EVENT_TYPE_ACTIVITY_FAILED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_TYPE_WORKFLOW_STARTED":   1,
		"EVENT_TYPE_WORKFLOW_COMPLETED": 2,
		"EVENT_TYPE_WORKFLOW_FAILED":    3,
		"EVENT_TYPE_ACTIVITY_SCHEDULED": 4,
		"EVENT_TYPE_ACTIVITY_STARTED":   5,
		"EVENT_TYPE_ACTIVITY_COMPLETED": 6,
		"EVENT_TYPE_ACTIVITY_FAILED":    7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_workflow_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_workflow_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{1}
}

type GetWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowsRequest) Reset() {
	*x = GetWorkflowsRequest{}
	mi := &file_api_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowsRequest) ProtoMessage() {}

func (x *GetWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *GetWorkflowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetWorkflowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowExecution   `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowsResponse) Reset() {
	*x = GetWorkflowsResponse{}
	mi := &file_api_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowsResponse) ProtoMessage() {}

func (x *GetWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkflowsResponse) GetWorkflows() []*WorkflowExecution {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *GetWorkflowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetWorkflowHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryRequest) Reset() {
	*x = GetWorkflowHistoryRequest{}
	mi := &file_api_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryRequest) ProtoMessage() {}

func (x *GetWorkflowHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*WorkflowEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryResponse) Reset() {
	*x = GetWorkflowHistoryResponse{}
	mi := &file_api_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryResponse) ProtoMessage() {}

func (x *GetWorkflowHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowHistoryResponse) GetEvents() []*WorkflowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_api_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=api.workflow.v1.WorkflowStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_api_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

type WorkflowExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=api.workflow.v1.WorkflowStatus" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Input         string                 `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_api_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WorkflowExecution) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *WorkflowExecution) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *WorkflowExecution) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	EventType     EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=api.workflow.v1.EventType" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	ActivityName  string                 `protobuf:"bytes,6,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_api_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_api_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WorkflowEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WorkflowEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WorkflowEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *WorkflowEvent) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

var File_api_workflow_proto protoreflect.FileDescriptor

const file_api_workflow_proto_rawDesc = "" +
	"\n" +
	"\x12api/workflow.proto\x12\x0fapi.workflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x13GetWorkflowsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x80\x01\n" +
	"\x14GetWorkflowsResponse\x12@\n" +
	"\tworkflows\x18\x01 \x03(\v2\".api.workflow.v1.WorkflowExecutionR\tworkflows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"<\n" +
	"\x19GetWorkflowHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"T\n" +
	"\x1aGetWorkflowHistoryResponse\x126\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.api.workflow.v1.WorkflowEventR\x06events\"\\\n" +
	"\x16ExecuteWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"s\n" +
	"\x17ExecuteWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.api.workflow.v1.WorkflowStatusR\x06status\"\xb2\x02\n" +
	"\x11WorkflowExecution\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.api.workflow.v1.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05input\x18\x06 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\a \x01(\tR\x06output\"\xff\x01\n" +
	"\rWorkflowEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x129\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1a.api.workflow.v1.EventTypeR\teventType\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12#\n" +
	"\ractivity_name\x18\x06 \x01(\tR\factivityName*\xa8\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x04*\x92\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEVENT_TYPE_WORKFLOW_STARTED\x10\x01\x12!\n" +
	"\x1dEVENT_TYPE_WORKFLOW_COMPLETED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_WORKFLOW_FAILED\x10\x03\x12!\n" +
	"\x1dEVENT_TYPE_ACTIVITY_SCHEDULED\x10\x04\x12\x1f\n" +
	"\x1bEVENT_TYPE_ACTIVITY_STARTED\x10\x05\x12!\n" +
	"\x1dEVENT_TYPE_ACTIVITY_COMPLETED\x10\x06\x12\x1e\n" +
	"\x1aEVENT_TYPE_ACTIVITY_FAILED\x10\a2\xc3\x02\n" +
	"\x0fWorkflowService\x12[\n" +
	"\fGetWorkflows\x12$.api.workflow.v1.GetWorkflowsRequest\x1a%.api.workflow.v1.GetWorkflowsResponse\x12m\n" +
	"\x12GetWorkflowHistory\x12*.api.workflow.v1.GetWorkflowHistoryRequest\x1a+.api.workflow.v1.GetWorkflowHistoryResponse\x12d\n" +
	"\x0fExecuteWorkflow\x12'.api.workflow.v1.ExecuteWorkflowRequest\x1a(.api.workflow.v1.ExecuteWorkflowResponseB*Z(durablefuture/api/workflow/v1;workflowv1b\x06proto3"

var (
	file_api_workflow_proto_rawDescOnce sync.Once
	file_api_workflow_proto_rawDescData []byte
)

func file_api_workflow_proto_rawDescGZIP() []byte {
	file_api_workflow_proto_rawDescOnce.Do(func() {
		file_api_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_workflow_proto_rawDesc), len(file_api_workflow_proto_rawDesc)))
	})
	return file_api_workflow_proto_rawDescData
}

var file_api_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_workflow_proto_goTypes = []any{
	(WorkflowStatus)(0),                // 0: api.workflow.v1.WorkflowStatus
	(EventType)(0),                     // 1: api.workflow.v1.EventType
	(*GetWorkflowsRequest)(nil),        // 2: api.workflow.v1.GetWorkflowsRequest
	(*GetWorkflowsResponse)(nil),       // 3: api.workflow.v1.GetWorkflowsResponse
	(*GetWorkflowHistoryRequest)(nil),  // 4: api.workflow.v1.GetWorkflowHistoryRequest
	(*GetWorkflowHistoryResponse)(nil), // 5: api.workflow.v1.GetWorkflowHistoryResponse
	(*ExecuteWorkflowRequest)(nil),     // 6: api.workflow.v1.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil),    // 7: api.workflow.v1.ExecuteWorkflowResponse
	(*WorkflowExecution)(nil),          // 8: api.workflow.v1.WorkflowExecution
	(*WorkflowEvent)(nil),              // 9: api.workflow.v1.WorkflowEvent
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_api_workflow_proto_depIdxs = []int32{
	8,  // 0: api.workflow.v1.GetWorkflowsResponse.workflows:type_name -> api.workflow.v1.WorkflowExecution
	9,  // 1: api.workflow.v1.GetWorkflowHistoryResponse.events:type_name -> api.workflow.v1.WorkflowEvent
	0,  // 2: api.workflow.v1.ExecuteWorkflowResponse.status:type_name -> api.workflow.v1.WorkflowStatus
	0,  // 3: api.workflow.v1.WorkflowExecution.status:type_name -> api.workflow.v1.WorkflowStatus
	10, // 4: api.workflow.v1.WorkflowExecution.start_time:type_name -> google.protobuf.Timestamp
	10, // 5: api.workflow.v1.WorkflowExecution.end_time:type_name -> google.protobuf.Timestamp
	1,  // 6: api.workflow.v1.WorkflowEvent.event_type:type_name -> api.workflow.v1.EventType
	10, // 7: api.workflow.v1.WorkflowEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: api.workflow.v1.WorkflowService.GetWorkflows:input_type -> api.workflow.v1.GetWorkflowsRequest
	4,  // 9: api.workflow.v1.WorkflowService.GetWorkflowHistory:input_type -> api.workflow.v1.GetWorkflowHistoryRequest
	6,  // 10: api.workflow.v1.WorkflowService.ExecuteWorkflow:input_type -> api.workflow.v1.ExecuteWorkflowRequest
	3,  // 11: api.workflow.v1.WorkflowService.GetWorkflows:output_type -> api.workflow.v1.GetWorkflowsResponse
	5,  // 12: api.workflow.v1.WorkflowService.GetWorkflowHistory:output_type -> api.workflow.v1.GetWorkflowHistoryResponse
	7,  // 13: api.workflow.v1.WorkflowService.ExecuteWorkflow:output_type -> api.workflow.v1.ExecuteWorkflowResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_workflow_proto_init() }
func file_api_workflow_proto_init() {
	if File_api_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_workflow_proto_rawDesc), len(file_api_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_workflow_proto_goTypes,
		DependencyIndexes: file_api_workflow_proto_depIdxs,
		EnumInfos:         file_api_workflow_proto_enumTypes,
		MessageInfos:      file_api_workflow_proto_msgTypes,
	}.Build()
	File_api_workflow_proto = out.File
	file_api_workflow_proto_goTypes = nil
	file_api_workflow_proto_depIdxs = nil
}
